### ISSUE TITLE
Unsubscribe isn't working as intended

### ISSUE THREAD

**Issue by JulianNorton** [codeforamerica/citygram#223] opened 2015-11-19 13:41 UTC
When I first registered, I hit enter a few times because I didn't realize it was working. As a consequence I get half a dozen emails a week now, and unsubscribing doesn't work.
![screen shot 2015-11-19 at 8 40 49 am](https://cloud.githubusercontent.com/assets/2412992/11272225/5813ec34-8e99-11e5-8a14-c037f5470309.png)

**Comment by bigfleet** [comment] 2015-11-20 21:29
@JulianNorton If you'll permit me, it looks like "subscribe" is the part that's not working as intended!

Would you like me to clean up the duplicates, or have you done it already?

**Comment by JulianNorton** [comment] 2015-11-20 21:31
I haven't been able to unsubscribe the duplicates. I'd just like one email. Thanks @bigfleet

**Comment by bigfleet** [comment] 2015-11-20 21:33
@JulianNorton When you say, "I haven't been able to", you mean, you have not made the effort?  Or you mean that you have attempted it, and have received an error?  Or that you have made the attempt, and the emails continue?

I'll contact your email with any further followup.  (We are likely to take a few approaches to this ticket based on our findings.)  Thanks for the ticket!

**Comment by JulianNorton** [comment] 2015-11-20 21:34
I've tried to, I click the link, get a confirmation screen, but I still get the same amount of emails anyway.

<img width="1192" alt="screen shot 2015-11-20 at 4 33 56 pm" src="https://cloud.githubusercontent.com/assets/2412992/11312510/8194a9ac-8fa4-11e5-886e-d014a2ef9b44.png">

**Comment by JulianNorton** [comment] 2015-11-27 13:36
@bigfleet I got 5 more emails yesterday
<img width="1123" alt="screen shot 2015-11-27 at 8 36 06 am" src="https://cloud.githubusercontent.com/assets/2412992/11442272/f497bff6-94e1-11e5-85a6-2861e02a0b87.png">

**Comment by bigfleet** [comment] 2015-11-28 22:48
@JulianNorton My apologies, I didn't see you were in NYC.  citygram.nyc is an independent installation (I'm working on smoothing the process of error reporting.)  Paging @dirkkelly!

**Comment by dirkkelly** [comment] 2015-12-02 00:54
@JulianNorton thanks for the report, give me a couple of days and I'll get back to you. Cc/ @excepttheweasel you were reporting something similar right? Thanks for patience everyone, juggling a few balls at the moment including traveling.

**Comment by JulianNorton** [comment] 2015-12-10 15:00
@dirkkelly I got 5 more emails this morning.

**Comment by dirkkelly** [comment] 2015-12-10 18:07
@JulianNorton Looking it to this now. You have 7 overall, I'm going to reduce to only one per geometry.

**Comment by dirkkelly** [comment] 2015-12-10 18:17
All sorted, you're down to 2 active subscriptions for the two unique geoms.

You had 17 over two email addresses, let me know if there's others I should look for. 

## Deleted Dupe Geoms by ID

```
Subscription.where(email_address: "julian.norton@gmail.com").count => 7
Subscription.where(email_address: "julian.norton@gmail.com").all.map(&:inspect)

[
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000008936384B837B52C0997E1214666D4440340A4A97447B52C0997E1214666D4440340A4A97447B52C01FCBF9EDC46D44408936384B837B52C01FCBF9EDC46D44408936384B837B52C0997E1214666D4440\", :updated_at=>2015-10-13 15:42:29 UTC, :created_at=>2014-10-27 16:17:59 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-13 15:42:29 UTC, :id=>\"e77476c0-cff7-42e3-b091-1947f3e71d9b\", :last_notified=>nil}>",
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-11-12 14:16:56 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-11-12 14:16:56 UTC, :id=>\"d934329d-0816-4eb9-98ce-f587fcc9fc22\", :last_notified=>nil}>",
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-13 15:44:09 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>nil, :id=>\"be034f48-0866-4382-b190-d0893bdfd61a\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-15 12:18:20 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-15 12:18:20 UTC, :id=>\"1b84636d-3e48-4bff-bb35-a937fcc00c88\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-15 12:25:50 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-15 12:25:50 UTC, :id=>\"3d21f96d-bc9d-42dd-b92f-07015217a1a3\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-11-05 13:08:45 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-11-05 13:08:45 UTC, :id=>\"61d255e4-5c93-4f2d-91e5-04a71cefe55e\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-11-12 14:16:49 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-11-05 13:08:45 UTC, :id=>\"b79ef500-3b60-4d4c-af9f-ef0e6ff37d36\", :last_notified=>nil}>"
]

Subscription.where(id: ["d934329d-0816-4eb9-98ce-f587fcc9fc22", "be034f48-0866-4382-b190-d0893bdfd61a", "1b84636d-3e48-4bff-bb35-a937fcc00c88", "3d21f96d-bc9d-42dd-b92f-07015217a1a3", "61d255e4-5c93-4f2d-91e5-04a71cefe55e"]).map(&:delete)
```

## Deleted all due to dupe geom

```
Subscription.where(email_address: "julian.norton+citygram@gmail.com").count => 
Subscription.where(email_address: "julian.norton+citygram@gmail.com").all.map(&:inspect)

=> [
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-13 15:44:09 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>nil, :id=>\"9a179bc9-62f1-464d-89c4-1a5f20bf2e5c\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-13 15:44:09 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>nil, :id=>\"17266c22-a33b-4ed2-b87c-83ec9ce10ccd\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-13 15:44:09 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>nil, :id=>\"94fb9b13-a74e-4988-be5c-c14b52c59478\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-13 15:44:09 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>nil, :id=>\"880feef6-797c-444a-878e-22c1aa38ff4d\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-15 12:24:03 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-15 12:24:03 UTC, :id=>\"31c2d03d-8eeb-4bab-997d-e9f688bfeda5\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-22 17:56:03 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-22 17:56:03 UTC, :id=>\"7ad95190-6681-4876-b344-8c21c992f482\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-11-05 13:09:29 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-11-05 13:09:29 UTC, :id=>\"7fa7173f-fb18-4c6e-b57e-0369fcf0f95c\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-11-20 21:33:44 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-11-20 21:33:44 UTC, :id=>\"001f6775-57ae-4f12-b359-89970e7b7ca0\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-22 17:55:41 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-22 17:55:41 UTC, :id=>\"904fd01b-88af-4d8c-aecf-1050ae7f5f6b\", :last_notified=>nil}>", 
"#<Citygram::Models::Subscription @values={:geom=>\"0103000020E610000001000000050000004A64104C4E7E52C061B27AFC056644401F3A13A60F7E52C061B27AFC056644401F3A13A60F7E52C0E7FE61D6646644404A64104C4E7E52C0E7FE61D6646644404A64104C4E7E52C061B27AFC05664440\", :updated_at=>2015-10-22 17:55:50 UTC, :created_at=>2015-10-13 15:44:09 UTC, :publisher_id=>1, :channel=>\"email\", :phone_number=>\"\", :email_address=>\"julian.norton+citygram@gmail.com\", :webhook_url=>nil, :unsubscribed_at=>2015-10-22 17:55:50 UTC, :id=>\"b79ef500-3b60-4d4c-af9f-ef0e6ff37d36\", :last_notified=>nil}>"
]

Subscription.where(email_address: "julian.norton+citygram@gmail.com").all.map(&:delete)
```

**Comment by dirkkelly** [comment] 2015-12-10 18:18
Looks like there could be even more

```
Subscription.where("email_address LIKE 'julian.norton%'").count => 12
```

**Comment by dirkkelly** [comment] 2015-12-10 18:19
All clear (I forgot to delete the last ten earlier), you're down to two subscription @JulianNorton 

```
Subscription.where("email_address LIKE 'julian.norton%'").count => 2
```

**Comment by JulianNorton** [comment] 2015-12-10 19:58
Great, thanks @dirkkelly. I'm not sure if this should be closed out because my individual case is resolved, or if it should remain open because the email unsubscribe wasn't working.

**Comment by bigfleet** [comment] 2015-12-10 20:28
I think we should refile as a couple of items:

1. Allow one subscription per channel to a particular contact for a particular geometry.
1. Provide feedback when using the enter key re: subscription success or failure

The first will take care of the apparent lack of success in unsubscribing.  (You were unsub'ing successfully, but there were still several more for you.)

The second will ensure that you have a proper feedback look for the behavior.

What do you think @JulianNorton @dirkkelly?

Thanks for playing along, as well.

**Comment by JulianNorton** [comment] 2015-12-10 20:36
That sounds good @bigfleet

**Comment by bigfleet** [comment] 2015-12-10 21:17
With those filed, I'll close this!  Thanks.

**Closed by bigfleet** 2015-12-10 21:17 UTC

**Comment by dirkkelly** [comment] 2015-12-11 13:24
Cheers @bigfleet
